import { LANDING_WORDMARK_WIDTH } from "navigation/RootStackNavigator/constants";

const SPLASH_SCREEN_HIDE_DELAY = 500;
const ENDING_WORDMARK_ANIMATION_SCALE = 0.8;
const STARTING_WORDMARK_WIDTH = LANDING_WORDMARK_WIDTH / ENDING_WORDMARK_ANIMATION_SCALE;

export { SPLASH_SCREEN_HIDE_DELAY, STARTING_WORDMARK_WIDTH };
